name: Asm CI

on:
  pull_request

jobs:
  tests:
    name: Testing asm
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: |
        sudo apt install binutils g++ cmake nasm
        sudo apt install haskell-stack netbase
        stack upgrade
        stack install random optparse-applicative
        stack ghc -- -o test test.hs

    - name: build
      run: ./build.sh

    - name: test sub
      run: ./test sub --bin ./build/sub --max-qwords 128 --tests 1000

    - name: test mul
      run: ./test mul --bin ./build/mul --max-qwords 128 --tests 1000
